# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my_messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11my_messages.proto\"5\n\tVideoFeed\x12\x18\n\x0bmessageFeed\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x42\x0e\n\x0c_messageFeed\"E\n\x0bInstruction\x12\x1f\n\x12messageInstruction\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x15\n\x13_messageInstructionb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIDEOFEED._serialized_start=21
  _VIDEOFEED._serialized_end=74
  _INSTRUCTION._serialized_start=76
  _INSTRUCTION._serialized_end=145
# @@protoc_insertion_point(module_scope)
